### PR TITLE
Switch to `.env` file

### PR DESCRIPTION
**Pull request by samuelburnham**
Test PR for `end2end` configurable tests

### CODE REVIEW

**Comment by samuelburnham** [comment]
!test

**Comment by samuelburnham** [comment]
!test

**Review by storojs72 — APPROVED** [review]

**Comment by samuelburnham** [comment]
!test NOVA_URL=https://github.com/lurk-lab/Nova.git NOVA_COMMIT=ea4f75c225cb29f523780858ec84f1ff51c229bc NOVA_TEST_NAME=solidity_compatibility_e2e_pasta

**Comment by storojs72** [comment]
!test NOVA_URL=https://github.com/lurk-lab/Nova.git NOVA_COMMIT=d5f5fb5e557b99cb111f2d5693aa34fe30722750 NOVA_TEST_NAME=solidity_compatibility_e2e_pasta

**Pull request merged**
